import React from 'react';import {Routes,Route,Navigate} from 'react-router-dom';
import Landing from './pages/Landing';
import AboutUs from './pages/AboutUs';
import HowItWorksPage from './pages/HowItWorksPage';
import ForAuditors from './pages/ForAuditors';
import ForBrands from './pages/ForBrands';
import FaqPage from './pages/FaqPage';
import ContactUs from './pages/ContactUs';
import LegalPage from './pages/LegalPage';
import UserDashboard from './user/UserDashboard';import FindTasks from './user/FindTasks';import TaskDetails from './user/TaskDetails';import MyTasks from './user/MyTasks';import Wallet from './user/Wallet';import Profile from './user/Profile';import CompleteTask from './user/CompleteTask';import Notifications from './user/Notifications';import Support from './user/Support';
import AdminDashboard from './admin/AdminDashboard';import Verification from './admin/Verification';import Users from './admin/Users';import Campaigns from './admin/Campaigns';import GenericAdmin from './admin/GenericAdmin';import CreateCampaign from './admin/CreateCampaign';import TaskBuilder from './admin/TaskBuilder';import SurveyBuilder from './admin/SurveyBuilder';import SubmissionReview from './admin/SubmissionReview';import Payments from './admin/Payments';import Reports from './admin/Reports';import Settings from './admin/Settings';
import WebsiteCMS from './admin/WebsiteCMS';
import KycReview from './admin/KycReview';import UserRisk from './admin/UserRisk';import Clients from './admin/Clients';import Locations from './admin/Locations';import BulkImport from './admin/BulkImport';import Disputes from './admin/Disputes';import Growth from './admin/Growth';import RolesPermissions from './admin/RolesPermissions';import AuditLogs from './admin/AuditLogs';import NotificationTemplates from './admin/NotificationTemplates';import PayoutApproval from './admin/PayoutApproval';
import {WorkflowBuilder,QCCenter,FraudCenter,FinanceCenter,AutomationCenter,TrainingCenter,CommunicationsCenter,SystemOperations,ApiWebhooks} from './admin/AdvancedModules';
import {ClientTeam,ReportBuilder,ScheduledReports,AdvancedAnalytics} from './client/EnterpriseClient';
import {UserTraining,OfflineMode} from './user/AdvancedUser';
import Vendors from './admin/Vendors';import {VendorDashboard,VendorMembers,VendorTasks,VendorPayments,VendorProfile} from './vendor/VendorPanel';
import {OperationsControlTower,VendorCommercials,VendorContracts,VendorSettlements,VendorCapacity,VendorBidding,VendorPerformance,WorkforceManagement,SmartAllocation,BudgetControl,GovernanceCompliance,WhiteLabel,TaskSourcing} from './admin/V5Enterprise';
import {VendorCommercialView,VendorContractView,VendorCapacityView,VendorBidsView,VendorSettlementView,VendorWorkforceView,VendorWhiteLabelView} from './vendor/V5Vendor';
import ClientDashboard from './client/ClientDashboard';import ClientCampaigns from './client/ClientCampaigns';import ClientReports from './client/ClientReports';import Billing from './client/Billing';import ClientTasks from './client/ClientTasks';import ClientMessages from './client/ClientMessages';import ClientSettings from './client/ClientSettings';
export default function App(){return <Routes>
<Route path='/' element={<Landing/>}/>
<Route path='/about' element={<AboutUs/>}/>
<Route path='/how-it-works' element={<HowItWorksPage/>}/>
<Route path='/for-auditors' element={<ForAuditors/>}/>
<Route path='/for-brands' element={<ForBrands/>}/>
<Route path='/faq' element={<FaqPage/>}/>
<Route path='/contact' element={<ContactUs/>}/>
<Route path='/terms' element={<LegalPage title="Terms & Conditions"/>}/>
<Route path='/privacy' element={<LegalPage title="Privacy Policy"/>}/>
<Route path='/user' element={<UserDashboard/>}/><Route path='/user/find-tasks' element={<FindTasks/>}/><Route path='/user/tasks/:id' element={<TaskDetails/>}/><Route path='/user/tasks/:id/complete' element={<CompleteTask/>}/><Route path='/user/my-tasks' element={<MyTasks/>}/><Route path='/user/wallet' element={<Wallet/>}/><Route path='/user/bell' element={<Notifications/>}/><Route path='/user/profile' element={<Profile/>}/><Route path='/user/support' element={<Support/>}/><Route path='/user/training' element={<UserTraining/>}/><Route path='/user/offline' element={<OfflineMode/>}/>
<Route path='/admin' element={<AdminDashboard/>}/><Route path='/admin/control-tower' element={<OperationsControlTower/>}/><Route path='/admin/vendor-commercials' element={<VendorCommercials/>}/><Route path='/admin/vendor-contracts' element={<VendorContracts/>}/><Route path='/admin/vendor-settlements' element={<VendorSettlements/>}/><Route path='/admin/vendor-capacity' element={<VendorCapacity/>}/><Route path='/admin/vendor-bidding' element={<VendorBidding/>}/><Route path='/admin/vendor-performance' element={<VendorPerformance/>}/><Route path='/admin/vendor-workforce' element={<WorkforceManagement/>}/><Route path='/admin/smart-allocation' element={<SmartAllocation/>}/><Route path='/admin/budget-control' element={<BudgetControl/>}/><Route path='/admin/governance' element={<GovernanceCompliance/>}/><Route path='/admin/white-label' element={<WhiteLabel/>}/><Route path='/admin/task-sourcing' element={<TaskSourcing/>}/><Route path='/admin/users' element={<Users/>}/><Route path='/admin/users/kyc' element={<KycReview/>}/><Route path='/admin/users/risk' element={<UserRisk/>}/><Route path='/admin/clients' element={<Clients/>}/><Route path='/admin/vendors' element={<Vendors/>}/><Route path='/admin/campaigns' element={<Campaigns/>}/><Route path='/admin/campaigns/new' element={<CreateCampaign/>}/><Route path='/admin/tasks' element={<TaskBuilder/>}/><Route path='/admin/tasks/survey-builder' element={<SurveyBuilder/>}/><Route path='/admin/tasks/bulk-import' element={<BulkImport/>}/><Route path='/admin/locations' element={<Locations/>}/><Route path='/admin/verification' element={<Verification/>}/><Route path='/admin/verification/:id' element={<SubmissionReview/>}/><Route path='/admin/disputes' element={<Disputes/>}/><Route path='/admin/growth' element={<Growth/>}/><Route path='/admin/payments' element={<Payments/>}/><Route path='/admin/payouts' element={<PayoutApproval/>}/><Route path='/admin/reports' element={<Reports/>}/><Route path='/admin/notifications' element={<NotificationTemplates/>}/><Route path='/admin/roles' element={<RolesPermissions/>}/><Route path='/admin/audit-logs' element={<AuditLogs/>}/><Route path='/admin/website-cms' element={<WebsiteCMS/>}/><Route path='/admin/settings' element={<Settings/>}/><Route path='/admin/workflows' element={<WorkflowBuilder/>}/><Route path='/admin/qc' element={<QCCenter/>}/><Route path='/admin/fraud' element={<FraudCenter/>}/><Route path='/admin/finance' element={<FinanceCenter/>}/><Route path='/admin/automations' element={<AutomationCenter/>}/><Route path='/admin/training' element={<TrainingCenter/>}/><Route path='/admin/communications' element={<CommunicationsCenter/>}/><Route path='/admin/system' element={<SystemOperations/>}/><Route path='/admin/api-webhooks' element={<ApiWebhooks/>}/><Route path='/admin/submissions' element={<GenericAdmin title='Submissions'/>}/>
<Route path='/vendor' element={<VendorDashboard/>}/><Route path='/vendor/commercials' element={<VendorCommercialView/>}/><Route path='/vendor/contracts' element={<VendorContractView/>}/><Route path='/vendor/capacity' element={<VendorCapacityView/>}/><Route path='/vendor/bids' element={<VendorBidsView/>}/><Route path='/vendor/settlements' element={<VendorSettlementView/>}/><Route path='/vendor/workforce' element={<VendorWorkforceView/>}/><Route path='/vendor/white-label' element={<VendorWhiteLabelView/>}/><Route path='/vendor/members' element={<VendorMembers/>}/><Route path='/vendor/tasks' element={<VendorTasks/>}/><Route path='/vendor/payments' element={<VendorPayments/>}/><Route path='/vendor/profile' element={<VendorProfile/>}/>
<Route path='/client' element={<ClientDashboard/>}/><Route path='/client/campaigns' element={<ClientCampaigns/>}/><Route path='/client/tasks' element={<ClientTasks/>}/><Route path='/client/messages' element={<ClientMessages/>}/><Route path='/client/settings' element={<ClientSettings/>}/><Route path='/client/reports' element={<ClientReports/>}/><Route path='/client/billing' element={<Billing/>}/><Route path='/client/team' element={<ClientTeam/>}/><Route path='/client/report-builder' element={<ReportBuilder/>}/><Route path='/client/scheduled-reports' element={<ScheduledReports/>}/><Route path='/client/analytics' element={<AdvancedAnalytics/>}/><Route path='*' element={<Navigate to='/'/>}/></Routes>}
